#!/bin/sh
set -eu

LIB=.libs/libwayland-egl.so

# Official ABI, taken from the header.
REQ_FUNCS="
wl_egl_window_resize
wl_egl_window_create
wl_egl_window_destroy
wl_egl_window_get_attached_size
"

# Run the checks
source "$top_srcdir"/scripts/symbols-check
